### ISSUE TITLE
Help page  content

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/seasonal-calendar#12]
@sat01a commented on [Wed Oct 26 2016](https://github.com/AtlasOfLivingAustralia/IEK/issues/18)

---

@StephanievG commented on [Sun Oct 30 2016](https://github.com/AtlasOfLivingAustralia/IEK/issues/18#issuecomment-257127851)

Have added to following google doc "Calendar - data entry fields" tab - "help" information that goes against each of the proposed fields:
https://docs.google.com/spreadsheets/d/12cu2SzSJhaaNBzdHH6GKyfEQYX_rc8PEb4zneE1Suls/edit#gid=842624034

**Comment by sat01a** [comment]
This was covered as part of #3 #4

**Comment by sat01a** [comment]
https://upsource.ala.org.au/seasonal-calendar/review/SC-CR-4

**Comment by javier-molina** [comment]
@sathishala  a couple of things to address imo

- USE Section:

 - Limitations tooltip is massive, it could be covered by the top banner. I suggest to reduce the content and possibly add a url for further details if needed.

- Feature Information section
 - Feature Images URL, missing hyperlink to images.ala.org.au

**Comment by sat01a** [comment]
Done- (Limited tool tip info. Removed hyperlink text.)
