### ISSUE TITLE
Add Ansible configurations to deploy to seasonal calendar test server

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/seasonal-calendar#14]
An initial Ansible configuration has been added to ansible-inventories and ala-install by copy-pasting the ecodata Ansible configurations, based on knowing that Grails and MongoDB are used somehow by this application and ecodata used both Grails and MongoDB. 

Having no further knowledge about the development patterns used for this, I am leaving the rest to one of the developers who has the requisite knowledge to complete the task.

The stub code that you will need to modify is:

https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/seasonalcalendar-test.yml

https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/seasonalcalendar/tasks/main.yml

https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/seasonalcalendar/templates/seasonalcalendar-config.properties

https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/seasonalcalendar/vars/main.yml

https://github.com/AtlasOfLivingAustralia/ansible-inventories/blob/master/fc-test.ala.org.au

Once that one is created and tested, the other two can be copy/pasted simply, so no need to open other tasks for them.

**Comment by ansell** [comment]
Note that when I created the ansible configurations above I was not aware that fc-test.ala.org.au and related host names were actually from the Field Capture project. I have opened a separate issue to decide on DNS names: #16 

I will change the references in the test configurations when we decide on new names and get servers operational for that.

**Comment by ansell** [comment]
References changed from seasonal-calendar to calendars. Basic deploy working to calendars-test.ala.org.au, which is physically located on ala-keef.it.csiro.au.

All further ansible related issues are left to application developers.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/seasonal-calendar/review/SC-CR-3
https://upsource.ala.org.au/ala-install/review/AI-CR-17

https://github.com/AtlasOfLivingAustralia/ansible-inventories/commit/b3999520de7d72f556369a6844d3cc46bf329caa

**Comment by ansell** [comment]
I was able to redeploy the last version built by Travis to calendars-test.ala.org.au. Closing this issue now but can reopen if you find it isn't working properly.
