### ISSUE TITLE
Decide on DNS name for the Seasonal Calendar website

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/seasonal-calendar#16]
Hi Rebecca (@rp-ala),

We need new DNS names for the Seasonal Calendar website and the test versions of it. So far Sathish and Javier have been reusing servers from the Field Capture project, fc.ala.org.au  / fc-dev.ala.org.au / fc-test.ala.org.au.

We need to decide on some dedicated names to create new servers to avoid reusing resources from Field Capture in this project.

@sat01a suggested sc.ala.org.au / sc-dev.ala.org.au / sc-test.ala.org.au

Thanks,

Peter

**Comment by rp-ala** [comment]
Hi Peter - perhaps calendars.ala.org.au, calendars-dev…., calendars-test…..?

**Comment by ansell** [comment]
calendars sounds good for me. Matt has created calendars-test.ala.org.au as a CNAME for ala-keef.it.csiro.au, and I will test ansible deployment there today. Other hostnames can be created next week when Sathish and Javier have a better idea of the specs that they want for those servers and whether they can be colocated with other existing low-traffic servers.
