### ISSUE TITLE
Design and implement project level metadata

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/seasonal-calendar#3]

**Comment by sat01a** [comment]
Notes from Stephanie:
See google doc "Calendar-data entry fields" for fields: 
https://docs.google.com/spreadsheets/d/12cu2SzSJhaaNBzdHH6GKyfEQYX_rc8PEb4zneE1Suls/edit#gid=842624034

**Comment by sat01a** [comment]
https://upsource.ala.org.au/seasonal-calendar/review/SC-CR-4

**Comment by javier-molina** [comment]
@sathishala I am seeing a few errors while running unit tests, in particular these below:

au.org.ala.calendar.CalendarServiceSpec#test CRUD operations for calendars
au.org.ala.calendar.CalendarSpec#test required fields in a new Calendar


Would you mind updating the tests to cater for the new fields introduced?

When that's done I will enable the test cycle in travis build.

Ta.

**Comment by sat01a** [comment]
Fixed failed unit test.
