### ISSUE TITLE
GET - list of collections from Profiles

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/seasonal-calendar#45]
As an admin
I want to see a list of collection names
So I can select the one I want

This is the issue for the web service to allow the user to GET the collection IDs and names available.

There is an IEK tag for collections in profiles. It would be preferable if only IEK tagged collections were returned by this call.

Issue #41 deals with the user interface allowing the user to select the collection and submit the request.

**Comment by RobinaSanderson** [comment]
Hi @NatRB and @m-hope If it saves time in the first sprint, could we ignore this and just get the admin to enter the collection name or id?

**Comment by Rita-C** [comment]
Implemented a profile service call for retrieving Optus(es) by a tag abbreviation.
e.g. http://localhost:8099/profile-service/tags/IEK/opuses

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-200

**Comment by RobinaSanderson** [comment]
Closing. No longer required for seasonal calendars as the act of creating a new seasonal calendar with create an associated collection in profiles.
