### ISSUE TITLE
Upgrade to grails 3

### ISSUE THREAD

**Issue by patkyn** [AtlasOfLivingAustralia/seasonal-calendar#67]

**Comment by sbearcsiro** [comment]
Seasonal Calendar app: https://github.com/AtlasOfLivingAustralia/seasonal-calendar/tree/grails3
ALA Map plugin: https://github.com/AtlasOfLivingAustralia/ala-map-plugin/tree/grails3
Profile-service app (fairly out of date): https://github.com/AtlasOfLivingAustralia/profile-service/tree/grails3

**Comment by m-hope** [comment]
This issue is no longer relevant with the changes to using Angular for the front-end.
