### ISSUE TITLE
Implement permission filters to handle security of the calendars.

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/seasonal-calendar#7]
@sat01a commented on [Wed Oct 26 2016](https://github.com/AtlasOfLivingAustralia/IEK/issues/13)

Protect sensitive resources. (like edit/save/create) based on permission filters.

**Comment by javier-molina** [comment]
- Add SC_ADMIN role to admin role validation.
- Besides admin, the owner of the calendar is the only person that can edit or delete it.
- Add server side validation for required fields, calendar name, season period, etc.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/seasonal-calendar/review/SC-CR-2

Please note that constraints for embedded domain classes seem to be ignored by Grails

**Comment by sat01a** [comment]
Hi Javier, 

Common security permission filter doesn't seems to have been applied.

For example code: Refer ecodata Checkpermission filter.

Thanks

**Comment by javier-molina** [comment]
AccessFilter and PreAuthorise annotation added.
