### ISSUE TITLE
Allow non-admin to create and edit calendar.

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/seasonal-calendar#8]
@sat01a commented on [Wed Oct 26 2016](https://github.com/AtlasOfLivingAustralia/IEK/issues/14)

**Comment by javier-molina** [comment]
Admins and users will share the same screen to edit calendars with the following changes:

- For a non admin user the list of calendars should have a heading the reads: "My Calendars", for admins it has to read "All calendars"
- Show details for Logged in user.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/seasonal-calendar/review/SC-CR-5
